config/routes.rb
CSCECE517Program1::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  get "search/index"

  get "statistics/index"

  get "home/index"
  get 'home' => 'home#index'

  resources :posts do
    resources :comments
  end

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  attr_accessible :comment

  def self.search(search)
    if search
      find(:all, :conditions => ['comment LIKE ?', "%#{search}%"])
    else
      #find(:all)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_filter :authorize_user, :only => [:index, :show]
  skip_before_filter :authorize_admin, :except => [:edit, :destroy]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  #def create
  #  @comment = Comment.new(params[:comment])
  #
  #  respond_to do |format|
  #    if @comment.save
  #      format.html { redirect_to @comment, :notice => 'Comment was successfully created.' }
  #      format.json { render :json => @comment, :status => :created, :location => @comment }
  #    else
  #      format.html { render :action => "new" }
  #      format.json { render :json => @comment.errors, :status => :unprocessable_entity }
  #    end
  #  end
  #end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    @comment.user_id = session[:user_id]

    #redirect_to post_path(@post)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), :notice => 'Comment was successfully created.' }
        format.json { render :json => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.json { render :json => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, :notice => 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <b><%= User.find(comment.user_id).name %> responded: </b>
  <%= comment.comment %>
  <% if session[:user_id] %>
    <% post = Post.find_by_id(comment.post_id) %>
    <% if User.find_by_id(session[:user_id]).is_admin? %>
      <%= link_to "Delete", post_comment_path(post, comment), :confirm => "Are you sure?", :method => :delete %>
    <% end %>
  <% end %>
</p>

app/views/comments/_comment_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<!--<table>-->
  <!--<tr>-->
    <!--<th>Comment</th>-->
    <!--<th>Post</th>-->
    <!--<th></th>-->
    <!--<th></th>-->
    <!--<th></th>-->
  <!--</tr>-->

<!--<% @comments.each do |comment| %>-->
  <!--<tr>-->
    <!--<td><%= comment.comment %></td>-->
    <!--<td><%= comment.post %></td>-->
    <!--<td><%= link_to 'Show', comment %></td>-->
    <!--<td><%= link_to 'Edit', edit_comment_path(comment) %></td>-->
    <!--<td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>-->
  <!--</tr>-->
<!--<% end %>-->
<!--</table>-->

<br />
<%= render @comments %>

<!--<%= link_to 'New Comment', new_comment_path %>-->

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>